version: "3"
services:
  persistence-api:
    # replace username/repo:tag with your name and image details
    image: nherbaut/variamos-model-persistence
    ports:
      - "8080:8080"
    environment:
      - "MONGO_PORT=27017"
      - "MONGO_HOST=mongo"
      - "GRPC_PORT=8080"
    
    
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db
  

volumes:
  mongo-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${MONGO_VOLUME}
    
